### ISSUE TITLE
Add Files API?

### ISSUE THREAD

**Issue by julien-noblet** [richardschneider/net-ipfs-mount#1]
Can you add Files API?

I think it could be a RW solution.

**Comment by richardschneider** [comment]
Checkout https://richardschneider.github.io/net-ipfs-api/api/Ipfs.Api.FileSystemApi.html  This is a C# binding to the Files API

**Comment by Kubuxu** [comment]
Files API looses most of it magic when you bind it to filesystem as most filesystem operations are not prepared for zero cost copy, move and so on.

**Comment by richardschneider** [comment]
@julien-noblet what are you asking for?  Do you want write access to the mounted drive from (1) any windows program or access to the IPFS File API?

**Comment by julien-noblet** [comment]
@richardschneider RW access could be great but when you change contents, hash is changing 😢 .
That's why I think, the IPFS File System API might be a workaround.

**Comment by richardschneider** [comment]
Why not use the [IPFS CLI](https://ipfs.io/docs/commands/); it provides access to the IPFS File System API.

    > ipfs add example.jpg
    added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH example.jpg

**Comment by julien-noblet** [comment]
Currently I doing this:
`
> ipfs add example.jpg
added QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH example.jpg
> ipfs files cp /ipfs/QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH /example.jpg
> ipfs files stat /
Qm........
> ipfs name publish Qm....

`
Then I 'm using ipfs-mount

**Comment by richardschneider** [comment]
Sorry, but I really don't understand the feature you want to add.  Could you elaborate what you want?

**Comment by julien-noblet** [comment]
Okay, I'll rephrase.

I am trying to access the root of local storage seamlessly. 

After reflection, I wonder if I use IPFS correctly.
