### ISSUE TITLE
Unable to write to z: folder - is this read-only?

### ISSUE THREAD

**Issue by sunk818** [richardschneider/net-ipfs-mount#7]
Won't let me copy files to IPFS folder in Z: drive.

Is this service only read-only?

**Comment by richardschneider** [comment]
Sorry, it is read-only for now.  There is [ipfs mfs](https://docs.ipfs.io/guides/concepts/mfs/) which could be supported for writing, but it has not yet been integrated with this package.

**Comment by sunk818** [comment]
Thanks for your reply. I was researching IPFS products that is friendly enough to be used by anyone. It would propel IPFS use. I think most can figure how to run a daemon, but pinning files is somewhat confusing. A file system mount would be ideal where your drive letter is your assigned IPFS hash and then you just pop files in that folder. As long as you have your daemon running, the content is available to anyone else that wants it...
