### ISSUE TITLE
Cant get ipfs-mount z  to work...  

### ISSUE THREAD

**Issue by lordfenixnc** [richardschneider/net-ipfs-mount#8]
C:\WINDOWS\system32>ipfs-mount z
One or more errors occurred.
An error occurred while sending the request.
Unable to connect to the remote server
No connection could be made because the target machine actively refused it 127.0.0.1:5001

i followed your steps.  Everything else seems to be working...

**Comment by richardschneider** [comment]
Are you running the IPFS daemon?

    > ipfs deamon
    > ipfs-mount z

**Comment by lordfenixnc** [comment]
thanks allot...  total noon  and  that worked...  i had to open 2 CMDs  to do it  but worked...         is it possible   to use a  Rclone drive  for storage?    i know  CMD cant see it but is there a way to get around it?   if you dont know  or not interested its cool  just figured i  would ask.... THANK YOU very much for helping out with my nood mistake

**Comment by richardschneider** [comment]
What is RClone? From the name I expect that is some cloud service that copies a drive.  If so, then its not needed for IPFS.  IPFS replicates the "files" across all the peers on network.

You can change the `ipfs daemon` command to `powershell start-process  -FilePath "ipfs.exe" -ArgumentList "daemon"`.  Basically it spawns a cmd shell for you.

**Comment by lordfenixnc** [comment]
Rclone allows you to Turn something like a Unlimited  Gdrive  into a hard drive.    makes it a Great for backup storage  and its encrypted.     Sad part is   constantly pulling from it  can cause  API limit ban.   So what i was thinking...    Rclone  Mounts  a Unlimited  Storage drive.  then  use that as a Location to PIN  IPFS.    Then was going to build a Kodi addon to access the media files   and  a Website.   also  want to tinker around with  IPFS mount for plex..      That is where im at.     Interested in helping?

**Comment by richardschneider** [comment]
`ipfs-mount` just maps a local drive onto the IPFS file system, via the [IPFS http client]( https://github.com/richardschneider/net-ipfs-api).  It will not help with your use case.

`ipfs` stores everything in what it calls the `repo`.  You could configure IPFS to use the Unlimited Storage driver for the repo.

From `ipfs init --help`

>ipfs uses a repository in the local file system. By default, the repo is
  located at ~/.ipfs. To change the repo location, set the $IPFS_PATH
  environment variable:

    set IPFS_PATH=drive:\ipfs-repo
