### ISSUE TITLE
BitTorrent support

### ISSUE THREAD

**Issue by lordvico** [richardschneider/net-ipfs-mount#9]
I know this is a bit out of scope of this project, but can you add support for BitTorrent protocol as well?

I tried [torrent-mount](https://github.com/mafintosh/torrent-mount) before but even using dokany it seems to not work on Windows. And it requires yet another dependency (node) to run...

Thanks in advance!

**Comment by richardschneider** [comment]
Sorry, this is IPFS support not BitTorrent.
